### ISSUE TITLE
Explanation and documentation

### ISSUE THREAD

**Issue by youmil** [O-CELL/nkebatch#1]
Can you publish a documentation with some explanation on how to execute the nkebatch program from shell ?

**Comment by echarlus** [comment]
Hello,
this library is not intended to be used from the command line but rather from another software. 
However, you can easily build a software to process payload data with the library. 
Check the README.md file for general instructions and for a sample that reads data from JSON file you can check ctl/main.go sample program.

**Comment by youmil** [comment]
Thank you for your response
