### ISSUE TITLE
Different result from BR_uncompress "official" program of nke

### ISSUE THREAD

**Issue by youmil** [O-CELL/nkebatch#2]
Hello,

I have a batch generated by the Press'O sensor.
When i decode this batch from the official windows BR_Uncompress program provided by NKE i have a different result from those generated by the CTL program.

Here the compress result : 100360a09f98280c0000703112420821c942082109b5ca11b27a21841092104208218450ab1ca1572b8410922c8410429225a1563942af5208210b212421644916925ae50859b52c2421841042082156 

Using ./br_uncompress -a 1 0,100,12 i have this results :
261572 0 900.000000 
261575 0 800.000000 
261576 0 800.000000 
261577 0 800.000000 
261578 0 800.000000 
261579 0 800.000000 
261580 0 800.000000 
261581 0 700.000000 
261582 0 800.000000
...

Using your library i have this result : 
261572 1147207680 900
261575 0 899
261576 0 0
261577 0 0
261578 0 0
261579 0 0
261580 0 0
261581 0 -1
261582 1 99

I used the same paramers for the decompression by defining them in the test.json  file: 
{
   ...
    "labelsize": 1,
    "series":
        [{
        "tag": 0,
        "resolution": 100,
        "type": 12
    }

I don't understand why the result are differents ? 
The results provided by the BR_Uncompress program seem right ! 
Is it a bug of the library ?

Best regards !

**Comment by echarlus** [comment]
Hi,
thanks for the report. This indeed seems to be a bug, we'll investigate...

**Comment by echarlus** [comment]
Hello,
we've identified and fixed the issue, you can fetch V0.0.4 which should work for you.
Let me know how it goes.
